<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="1.8m"
		durationms="107626"
		type="root"
		rid="c74061b03229ebe"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="THI1901453"
		rxversion="9.1.0.0"
		host="THSLT10102"
		osversion="Windows 10 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="en-US"
		dtnlanguage="en-US"
		screenresolution="1366x768"
		timestamp="6/28/2019 4:24:23 PM"
		timestampiso="2019-06-28T10:54:23"
		endtime="6/28/2019 4:26:11 PM"
		timeoutfactor="1"
		module="ToCraeteNewEstimate">
		<detail>
			ToCraeteNewEstimate
		</detail>
		<varbindings>
		</varbindings>
		<item
			timeRelativeToTestSuiteStartTime="00:00.000"
			timeRelativeToTestModuleStartTime="01:47.628"
			timeWallClock="16:26:11"
			time="00:00.000"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
	</activity>
</report>
